debug: false
service:
  address: ":5005"
  timeout:
    read: 10s
    write: 10s
webrtc:
  - address: ":2345"
    netType: tcp
  - address: ":5678"
    netType: udp
template:
  files:
    - "*.tmpl"
    - "*.html"
