debug: false
http:
  address: ":5005"
  timeout:
    read: 10s
    write: 10s
webrtc:
  pools:
    - netType: udp
    - netType: udp
      address: ":5678"
    - netType: tcp
      address: ":2345"
  iceServers:
    - "stun:stun.l.google.com:19302"
template:
  files:
    - "*.tmpl"
    - "*.html"
