debug: false
http:
  address: ":5005"
  timeout:
    read: 10s
    write: 10s
webrtc:
  pools:
    - network: udp
    - network: udp
      address: ":5678"
    - network: tcp
      address: ":2345"
  iceServers:
    - "stun:stun.l.google.com:19302"
