name: DockerCI

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/imssyang/gweb:${{ github.ref_name }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write
  id-token: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository - ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Login registry - ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.TOKEN }}

    - name: Build image - ${{ env.IMAGE }}
      working-directory: .
      shell: bash
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE }}

    - name: Push image - ${{ env.IMAGE }}
      id: push
      shell: bash
      run: |
        docker push ${{ env.IMAGE }} && \
        echo "image=${{ env.IMAGE }}" >> $GITHUB_OUTPUT

    - name: Metadata image - ${{ env.IMAGE }}
      run: env
      shell: bash
